services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    stdin_open: true
    tty: true
    volumes:
      - /mnt/rem/datasets/rest:/data
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - .venv/
        - action: rebuild
          path: ./pyproject.toml
        - action: rebuild
          path: ./uv.lock
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile.jupyter
    ports:
      - "9876:9876"
    volumes:
      - "/mnt/rem/datasets/rest:/data"
      - "./notebooks:/app/notebooks"
    environment:
      - JUPYTER_ENABLE_LAB=yes
    restart: 
      unless-stopped
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - .venv/
        - action: rebuild
          path: ./pyproject.toml
        - action: rebuild
          path: ./uv.lock